#*****************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# build.tcl: Tcl script for re-creating project 'multiple_mac_seq_cnn_hw_acc'
#
# Generated by Vivado on Tue Apr 05 20:26:22 +0200 2022
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (build.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/hw_cnn_lib.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_Layer2.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_Layer2_Output_MEM.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_Layer1.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_Layer1_Output_MEM.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_Layer3.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_Layer3_Output_MEM.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_MAC_layer1.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_MAC_layer2.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/LG_MAC_layer3.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/seq_cnn_hw_acc_S00_AXI.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/seq_cnn_hw_acc.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/Layer2_Debug.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/new/Layer3_Debug.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/imports/cnn_hwc_3232/component.xml"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/archive_project_summary.txt"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sim_1/new/TB_LG_Layer1.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sim_1/new/TB_LG_Layer3.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sim_1/new/TB_LG_layer2.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sim_1/new/TB_LG_MAC_layer2.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sim_1/new/tb_layer1_mem.vhd"
#    "C:/Users/Michael/Desktop/multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sim_1/new/tb_layer3_debug.vhd"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/src/hdl/hw_cnn_lib.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_Layer2.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_Layer2_Output_MEM.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_Layer1.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_Layer1_Output_MEM.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_Layer3.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_Layer3_Output_MEM.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_MAC_layer1.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_MAC_layer2.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/LG_MAC_layer3.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/seq_cnn_hw_acc_S00_AXI.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/seq_cnn_hw_acc.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/Layer2_Debug.vhd"]"\
 "[file normalize "$origin_dir/src/hdl/Layer3_Debug.vhd"]"\
# "[file normalize "$origin_dir/../multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/multiple_mac_seq_cnn_hw_acc.srcs/sources_1/imports/cnn_hwc_3232/component.xml"]"\
# "[file normalize "$origin_dir/../multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc/archive_project_summary.txt"]"\
 "[file normalize "$origin_dir/src/sim/TB_LG_Layer1.vhd"]"\
 "[file normalize "$origin_dir/src/sim/TB_LG_Layer3.vhd"]"\
 "[file normalize "$origin_dir/src/sim/TB_LG_layer2.vhd"]"\
 "[file normalize "$origin_dir/src/sim/TB_LG_MAC_layer2.vhd"]"\
 "[file normalize "$origin_dir/src/sim/tb_layer1_mem.vhd"]"\
 "[file normalize "$origin_dir/src/sim/tb_layer3_debug.vhd"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

#  set paths [list \
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/cnn_hwc_3232"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v20"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v12"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v11"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v10"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v09"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v08"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v07"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v06"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v05"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v04"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v02"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/multiple_mac_seq_cnn_hw_acc_v01"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/single_inst_seq_cnn_hw_acc_v06"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/single_inst_seq_cnn_hw_acc_v05"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/single_inst_seq_cnn_hw_acc_v04"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/single_inst_seq_cnn_hw_acc_v03"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/single_inst_seq_cnn_hw_acc_v02"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/single_inst_seq_cnn_hw_acc_v01"]"]"\
# "[file normalize "$origin_dir/../../AppData/Roaming/Xilinx/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v123"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v120"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v118"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v115"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v109"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v105"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v103"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v102"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v101"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v100"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v99"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v97"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v95"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v94"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v93"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v91"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v90"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v89"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v88"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v74"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v57"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v55"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v53"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v44"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v41"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v40"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v35"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v34"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v33"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v30"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v28"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v27"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v26"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v18"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v17"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v16"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v15"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v10"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v9"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v8"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v7"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v6"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v4"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v3"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v2"]"]"\
# "[file normalize "$origin_dir/../../AppData/Documents/2020_10_cnn_hardware_demo/src/vivado_src/vivado_ip_src/packaged/SEQ_CNN_HW_ACC_v1"]"]"\
# "[file normalize "$origin_dir/../../AppData/Desktop/myip_1.0"]"]"\
#  ]
#  foreach ipath $paths {
#    if { ![file isdirectory $ipath] } {
#      puts " Could not access $ipath "
#      set status false
#    }
#  }
#
#  return $status
#}

# Load the configuration file (assumed to be in the same directory as the script)
set config_file [file join [file dirname [info script]] "config.tcl"]
if {[file exists $config_file]} {
    source $config_file
} else {
    puts "Error: Configuration file not found: $config_file"
    exit 1
}

# Output the loaded project name for debugging
puts "Loaded project name: $project_name"

# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir [file dirname [info script]]

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ $project_name

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "build.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
#set orig_proj_dir "[file normalize "$origin_dir/../multiple_mac_seq_cnn_hw_acc.xpr/multiple_mac_seq_cnn_hw_acc"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project $project_name $origin_dir/$project_name -part xc7z020clg400-1

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "digilentinc.com:arty-z7-20:part0:1.1" -objects $obj
set_property -name "classic_soc_boot" -value "0" -objects $obj
set_property -name "compxlib.activehdl_compiled_library_dir" -value "$proj_dir/${_xil_proj_name_}.cache/compile_simlib/activehdl" -objects $obj
set_property -name "compxlib.funcsim" -value "1" -objects $obj
set_property -name "compxlib.modelsim_compiled_library_dir" -value "$proj_dir/${_xil_proj_name_}.cache/compile_simlib/modelsim" -objects $obj
set_property -name "compxlib.overwrite_libs" -value "0" -objects $obj
set_property -name "compxlib.questa_compiled_library_dir" -value "$proj_dir/${_xil_proj_name_}.cache/compile_simlib/questa" -objects $obj
set_property -name "compxlib.riviera_compiled_library_dir" -value "$proj_dir/${_xil_proj_name_}.cache/compile_simlib/riviera" -objects $obj
set_property -name "compxlib.timesim" -value "1" -objects $obj
set_property -name "compxlib.vcs_compiled_library_dir" -value "$proj_dir/${_xil_proj_name_}.cache/compile_simlib/vcs" -objects $obj
set_property -name "compxlib.xsim_compiled_library_dir" -value "" -objects $obj
set_property -name "corecontainer.enable" -value "0" -objects $obj
set_property -name "customized_default_ip_location" -value "" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "enable_optional_runs_sta" -value "0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "generate_ip_upgrade_log" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_interface_inference_priority" -value "" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "legacy_ip_repo_paths" -value "" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "platform.board_id" -value "arty-z7-20" -objects $obj
set_property -name "platform.default_output_type" -value "undefined" -objects $obj
set_property -name "platform.design_intent.datacenter" -value "undefined" -objects $obj
set_property -name "platform.design_intent.embedded" -value "undefined" -objects $obj
set_property -name "platform.design_intent.external_host" -value "undefined" -objects $obj
set_property -name "platform.design_intent.server_managed" -value "undefined" -objects $obj
set_property -name "platform.rom.debug_type" -value "0" -objects $obj
set_property -name "platform.rom.prom_type" -value "0" -objects $obj
set_property -name "platform.slrconstraintmode" -value "0" -objects $obj
set_property -name "preferred_sim_model" -value "rtl" -objects $obj
set_property -name "project_type" -value "Default" -objects $obj
set_property -name "pr_flow" -value "0" -objects $obj
set_property -name "revised_directory_structure" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "sim.use_ip_compiled_libs" -value "1" -objects $obj
set_property -name "simulator.activehdl_gcc_install_dir" -value "" -objects $obj
set_property -name "simulator.activehdl_install_dir" -value "" -objects $obj
set_property -name "simulator.modelsim_gcc_install_dir" -value "" -objects $obj
set_property -name "simulator.modelsim_install_dir" -value "" -objects $obj
set_property -name "simulator.questa_gcc_install_dir" -value "" -objects $obj
set_property -name "simulator.questa_install_dir" -value "" -objects $obj
set_property -name "simulator.riviera_gcc_install_dir" -value "" -objects $obj
set_property -name "simulator.riviera_install_dir" -value "" -objects $obj
set_property -name "simulator.vcs_gcc_install_dir" -value "" -objects $obj
set_property -name "simulator.vcs_install_dir" -value "" -objects $obj
set_property -name "simulator.xcelium_gcc_install_dir" -value "" -objects $obj
set_property -name "simulator.xcelium_install_dir" -value "" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj
set_property -name "source_mgmt_mode" -value "All" -objects $obj
set_property -name "target_language" -value "VHDL" -objects $obj
set_property -name "target_simulator" -value "XSim" -objects $obj
set_property -name "tool_flow" -value "Vivado" -objects $obj
set_property -name "webtalk.xsim_launch_sim" -value "393" -objects $obj
set_property -name "xpm_libraries" -value "" -objects $obj
set_property -name "xsim.array_display_limit" -value "1024" -objects $obj
set_property -name "xsim.radix" -value "hex" -objects $obj
set_property -name "xsim.time_unit" -value "ns" -objects $obj
set_property -name "xsim.trace_limit" -value "65536" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set IP repository paths
set obj [get_filesets sources_1]
if { $obj != {} } {
   set_property "ip_repo_paths" "[file normalize "$origin_dir/ip_repo"]" $obj

   # Rebuild user ip_repo's index before adding any source files
   update_ip_catalog -rebuild
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/hdl/hw_cnn_lib.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_Layer2.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_Layer2_Output_MEM.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_Layer1.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_Layer1_Output_MEM.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_Layer3.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_Layer3_Output_MEM.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_MAC_layer1.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_MAC_layer2.vhd"]\
 [file normalize "${origin_dir}/src/hdl/LG_MAC_layer3.vhd"]\
 [file normalize "${origin_dir}/src/hdl/seq_cnn_hw_acc_S00_AXI.vhd"]\
 [file normalize "${origin_dir}/src/hdl/seq_cnn_hw_acc.vhd"]\
 [file normalize "${origin_dir}/src/hdl/Layer2_Debug.vhd"]\
 [file normalize "${origin_dir}/src/hdl/Layer3_Debug.vhd"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "hdl/hw_cnn_lib.vhd"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "VHDL" -objects $file_obj
set_property -name "library" -value "hw_cnn_lib" -objects $file_obj
#
#set file "new/LG_Layer2.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_Layer2_Output_MEM.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_Layer1.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_Layer1_Output_MEM.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_Layer3.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_Layer3_Output_MEM.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_MAC_layer1.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_MAC_layer2.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/LG_MAC_layer3.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/seq_cnn_hw_acc_S00_AXI.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/seq_cnn_hw_acc.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/Layer2_Debug.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/Layer3_Debug.vhd"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "cnn_hwc_3232/component.xml"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "file_type" -value "IP-XACT" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "" -objects $file_obj
#
#set file "multiple_mac_seq_cnn_hw_acc/archive_project_summary.txt"
#set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "design_mode" -value "RTL" -objects $obj
set_property -name "edif_extra_search_paths" -value "" -objects $obj
set_property -name "elab_link_dcps" -value "1" -objects $obj
set_property -name "elab_load_timing_constraints" -value "1" -objects $obj
set_property -name "generic" -value "" -objects $obj
set_property -name "include_dirs" -value "" -objects $obj
set_property -name "lib_map_file" -value "" -objects $obj
set_property -name "loop_count" -value "1000" -objects $obj
set_property -name "name" -value "sources_1" -objects $obj
set_property -name "top" -value "seq_cnn_hw_acc" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "verilog_define" -value "" -objects $obj
set_property -name "verilog_uppercase" -value "0" -objects $obj
set_property -name "verilog_version" -value "verilog_2001" -objects $obj
set_property -name "vhdl_version" -value "vhdl_2k" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
set_property -name "constrs_type" -value "XDC" -objects $obj
set_property -name "name" -value "constrs_1" -objects $obj
set_property -name "target_constrs_file" -value "" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/src/sim/TB_LG_Layer1.vhd"]\
 [file normalize "${origin_dir}/src/sim/TB_LG_Layer3.vhd"]\
 [file normalize "${origin_dir}/src/sim/TB_LG_layer2.vhd"]\
 [file normalize "${origin_dir}/src/sim/TB_LG_MAC_layer2.vhd"]\
 [file normalize "${origin_dir}/src/sim/tb_layer1_mem.vhd"]\
 [file normalize "${origin_dir}/src/sim/tb_layer3_debug.vhd"]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
#set file "new/TB_LG_Layer1.vhd"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL" -objects $file_obj
#set_property -name "is_enabled" -value "1" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/TB_LG_Layer3.vhd"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/TB_LG_layer2.vhd"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/TB_LG_MAC_layer2.vhd"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/tb_layer1_mem.vhd"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj
#
#set file "new/tb_layer3_debug.vhd"
#set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
#set_property -name "file_type" -value "VHDL 2008" -objects $file_obj
#set_property -name "is_enabled" -value "0" -objects $file_obj
#set_property -name "is_global_include" -value "0" -objects $file_obj
#set_property -name "library" -value "xil_defaultlib" -objects $file_obj
#set_property -name "path_mode" -value "RelativeFirst" -objects $file_obj
#set_property -name "used_in" -value "synthesis simulation" -objects $file_obj
#set_property -name "used_in_simulation" -value "1" -objects $file_obj
#set_property -name "used_in_synthesis" -value "1" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "32bit" -value "0" -objects $obj
set_property -name "force_compile_glbl" -value "0" -objects $obj
set_property -name "force_no_compile_glbl" -value "0" -objects $obj
set_property -name "generate_scripts_only" -value "0" -objects $obj
set_property -name "generic" -value "" -objects $obj
set_property -name "hbs.configure_design_for_hier_access" -value "1" -objects $obj
set_property -name "hw_emu.debug_mode" -value "wdb" -objects $obj
set_property -name "include_dirs" -value "" -objects $obj
set_property -name "incremental" -value "1" -objects $obj
set_property -name "name" -value "sim_1" -objects $obj
set_property -name "nl.cell" -value "" -objects $obj
set_property -name "nl.incl_unisim_models" -value "0" -objects $obj
set_property -name "nl.process_corner" -value "slow" -objects $obj
set_property -name "nl.rename_top" -value "" -objects $obj
set_property -name "nl.sdf_anno" -value "1" -objects $obj
set_property -name "nl.write_all_overrides" -value "0" -objects $obj
set_property -name "simmodel_value_check" -value "1" -objects $obj
set_property -name "simulator_launch_mode" -value "off" -objects $obj
set_property -name "source_set" -value "sources_1" -objects $obj
set_property -name "systemc_include_dirs" -value "" -objects $obj
set_property -name "top" -value "tb_LG_Layer1" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj
set_property -name "transport_int_delay" -value "0" -objects $obj
set_property -name "transport_path_delay" -value "0" -objects $obj
set_property -name "unifast" -value "0" -objects $obj
set_property -name "verilog_define" -value "" -objects $obj
set_property -name "verilog_uppercase" -value "0" -objects $obj
set_property -name "xelab.dll" -value "0" -objects $obj
set_property -name "xsim.compile.tcl.pre" -value "" -objects $obj
set_property -name "xsim.compile.xsc.more_options" -value "" -objects $obj
set_property -name "xsim.compile.xvhdl.more_options" -value "" -objects $obj
set_property -name "xsim.compile.xvhdl.nosort" -value "1" -objects $obj
set_property -name "xsim.compile.xvhdl.relax" -value "1" -objects $obj
set_property -name "xsim.compile.xvlog.more_options" -value "" -objects $obj
set_property -name "xsim.compile.xvlog.nosort" -value "1" -objects $obj
set_property -name "xsim.compile.xvlog.relax" -value "1" -objects $obj
set_property -name "xsim.elaborate.coverage.celldefine" -value "0" -objects $obj
set_property -name "xsim.elaborate.coverage.dir" -value "" -objects $obj
set_property -name "xsim.elaborate.coverage.library" -value "0" -objects $obj
set_property -name "xsim.elaborate.coverage.name" -value "" -objects $obj
set_property -name "xsim.elaborate.coverage.type" -value "" -objects $obj
set_property -name "xsim.elaborate.debug_level" -value "typical" -objects $obj
set_property -name "xsim.elaborate.link.c" -value "" -objects $obj
set_property -name "xsim.elaborate.link.sysc" -value "" -objects $obj
set_property -name "xsim.elaborate.load_glbl" -value "1" -objects $obj
set_property -name "xsim.elaborate.mt_level" -value "auto" -objects $obj
set_property -name "xsim.elaborate.rangecheck" -value "0" -objects $obj
set_property -name "xsim.elaborate.relax" -value "1" -objects $obj
set_property -name "xsim.elaborate.sdf_delay" -value "sdfmax" -objects $obj
set_property -name "xsim.elaborate.snapshot" -value "" -objects $obj
set_property -name "xsim.elaborate.xelab.more_options" -value "" -objects $obj
set_property -name "xsim.elaborate.xsc.more_options" -value "" -objects $obj
set_property -name "xsim.simulate.add_positional" -value "0" -objects $obj
set_property -name "xsim.simulate.custom_tcl" -value "" -objects $obj
set_property -name "xsim.simulate.log_all_signals" -value "0" -objects $obj
set_property -name "xsim.simulate.no_quit" -value "0" -objects $obj
set_property -name "xsim.simulate.runtime" -value "1000ns" -objects $obj
set_property -name "xsim.simulate.saif" -value "" -objects $obj
set_property -name "xsim.simulate.saif_all_signals" -value "0" -objects $obj
set_property -name "xsim.simulate.saif_scope" -value "" -objects $obj
set_property -name "xsim.simulate.tcl.post" -value "" -objects $obj
set_property -name "xsim.simulate.wdb" -value "" -objects $obj
set_property -name "xsim.simulate.xsim.more_options" -value "" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]
set_property -name "name" -value "utils_1" -objects $obj

set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}
